const $=id=>document.getElementById(id);let allEvents=[];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const formatTime=value=>new Date(value).toLocaleString([], {hour:'2-digit',minute:'2-digit',day:'2-digit',month:'short'});
async function load(){try{const limit=$('event-limit').value,plate=$('plate-search').value.trim();const[a,e]=await Promise.all([fetch('api/analytics').then(r=>r.json()),fetch(`api/events?limit=${encodeURIComponent(limit)}&plate=${encodeURIComponent(plate)}`).then(r=>r.json())]);$('today').textContent=a.today;$('unique').textContent=a.unique_plates;$('total').textContent=a.total;$('confidence').textContent=a.avg_confidence==null?'—':`${Math.round(a.avg_confidence*100)}%`;allEvents=e.events;renderChart(a.hourly);renderTop(a.top_plates);renderEvents();renderLatest();loadCameras()}catch(error){console.error('Unable to refresh dashboard',error)}}
function renderChart(data){const max=Math.max(...data.map(x=>x.count),1);$('chart').innerHTML=data.length?data.map(x=>`<div class="bar-wrap"><div class="bar" style="height:${Math.max(4,x.count/max*155)}px" title="${x.count} detections"></div><span class="bar-label">${x.hour}:00</span></div>`).join(''):'<div class="empty">No detections yet</div>'}
function renderTop(data){const max=data[0]?.count||1;$('top').innerHTML=data.length?data.map(x=>`<div class="top-row"><strong>${esc(x.plate)}</strong><span>${x.count} detections</span><div class="track"><div class="fill" style="width:${x.count/max*100}%"></div></div></div>`).join(''):'<div class="empty">No plates yet</div>'}
function renderEvents(){const filter=$('camera-filter').value,data=filter?allEvents.filter(x=>x.camera===filter):allEvents;$('event-count').textContent=`${data.length} EVENTS`;$('events').innerHTML=data.length?data.map(x=>`<tr class="event-row" data-event-id="${x.id}" tabindex="0" role="button" aria-label="Open ${esc(x.plate)} detection"><td>${formatTime(x.captured_at)}</td><td>${esc(x.plate)}</td><td>${esc(x.direction)}</td><td><span class="type-tag">${esc(x.vehicle_color||'Unknown')}</span></td><td class="confidence">${x.confidence==null?'—':Math.round(x.confidence*100)+'%'}</td><td>${x.has_thumbnail?`<img class="plate-thumb" src="api/events/${x.id}/thumbnail" alt="Plate ${esc(x.plate)}">`:'—'}</td></tr>`).join(''):'<tr><td colspan="6" class="empty">No detections for this camera.</td></tr>'}
function renderLatest(){const event=allEvents[0];$('latest-plate').textContent=event?.plate||'—';$('latest-camera').textContent=event?.direction||'—';$('latest-time').textContent=event?formatTime(event.captured_at):'—';document.querySelector('.camera-preview').innerHTML=event?.has_vehicle_image?`<span>LIVE</span><img src="api/events/${event.id}/vehicle" alt="Vehicle ${esc(event.plate)}">`:`<span>LIVE</span><div class="camera-preview-icon">▣</div><p>Waiting for camera snapshot</p>`}
async function loadCameras(){const data=await fetch('api/cameras').then(r=>r.json());const selected=$('camera-filter').value;const options='<option value="">All cameras</option>'+data.cameras.map(c=>`<option value="${esc(c.name)}">${esc(c.name)}</option>`).join('');$('camera-filter').innerHTML=options;$('camera-filter-side').innerHTML=options;$('camera-filter').value=selected;$('camera-filter-side').value=selected;$('camera-count').textContent=data.cameras.length;$('camera-list').innerHTML=data.cameras.length?data.cameras.map(c=>`<div class="camera-item"><span class="camera-status"></span><div><strong>${esc(c.name)}</strong><small>${esc(c.location||'Location not set')}</small></div><button class="delete-camera" data-id="${c.id}" title="Remove camera">×</button></div>`).join(''):'<div class="empty">No cameras configured yet.</div>';$('network-cameras').innerHTML=data.cameras.length?data.cameras.slice(0,4).map(c=>`<div><i class="dot lime"></i><span>${esc(c.name)}</span><small>${esc(c.location||'Online')}</small></div>`).join(''):'<div class="empty">No cameras configured</div>';document.querySelectorAll('.delete-camera').forEach(b=>b.onclick=async()=>{if(confirm('Remove this camera?')){await fetch('api/cameras/'+b.dataset.id,{method:'DELETE'});loadCameras()}})}
async function addCamera(e){e.preventDefault();const body=Object.fromEntries(new FormData(e.target));const res=await fetch('api/cameras',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(res.ok){e.target.reset();loadCameras()}else{const err=await res.json();alert(err.error||'Could not add camera')}}
function syncFilter(source){const value=source.value;$('camera-filter').value=value;$('camera-filter-side').value=value;renderEvents()}
function toggleDrawer(open){$('camera-drawer').classList.toggle('open',open);$('drawer-backdrop').classList.toggle('open',open)}
function applySettings(settings){$('retention-days').value=settings.retention_days;const mqtt=settings.mqtt;$('mqtt-enabled').checked=mqtt.mqtt_enabled;$('mqtt-host').value=mqtt.mqtt_host;$('mqtt-port').value=mqtt.mqtt_port;$('mqtt-username').value=mqtt.mqtt_username;$('mqtt-client-id').value=mqtt.mqtt_client_id;$('mqtt-topic').value=mqtt.mqtt_topic;$('mqtt-discovery-prefix').value=mqtt.mqtt_discovery_prefix;$('mqtt-password').placeholder=settings.mqtt_password_configured?'Password saved: leave blank to keep it':'Leave blank when no password is required'}
async function loadSettings(){const settings=await fetch('api/settings').then(r=>r.json());applySettings(settings)}
async function saveRetention(e){e.preventDefault();const days=Number($('retention-days').value);const res=await fetch('api/settings',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({retention_days:days})});if(res.ok){const settings=await res.json();$('retention-days').value=settings.retention_days;load()}else{const error=await res.json();alert(error.error||'Could not save retention setting')}}
function mqttFormData(){return {mqtt_enabled:$('mqtt-enabled').checked,mqtt_host:$('mqtt-host').value.trim(),mqtt_port:Number($('mqtt-port').value),mqtt_username:$('mqtt-username').value.trim(),mqtt_password:$('mqtt-password').value,mqtt_client_id:$('mqtt-client-id').value.trim(),mqtt_topic:$('mqtt-topic').value.trim(),mqtt_discovery_prefix:$('mqtt-discovery-prefix').value.trim()}}
async function saveMqtt(e){if(e)e.preventDefault();const res=await fetch('api/settings',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({mqtt:mqttFormData()})});if(!res.ok){const error=await res.json();alert(error.error||'Could not save MQTT settings');return false}const settings=await res.json();$('mqtt-password').value='';applySettings(settings);return true}
async function testMqtt(){if(!await saveMqtt())return;const res=await fetch('api/mqtt/test',{method:'POST'});const result=await res.json();alert(res.ok?'MQTT discovery configuration published.':result.error||'MQTT connection failed')}
function openEvent(eventId){const event=allEvents.find(item=>item.id===Number(eventId));if(!event)return;$('modal-plate').textContent=event.plate;$('modal-image').innerHTML=event.has_vehicle_image?`<img src="api/events/${event.id}/vehicle" alt="Vehicle ${esc(event.plate)}">`:'<div class="modal-image-empty">No vehicle image received</div>';$('modal-details').innerHTML=`<div><span>Accuracy</span><b>${event.confidence==null?'—':Math.round(event.confidence*100)+'%'}</b></div><div><span>Timestamp</span><b>${esc(event.captured_at)}</b></div><div><span>Direction</span><b>${esc(event.direction)}</b></div><div><span>Vehicle color</span><b>${esc(event.vehicle_color||'Unknown')}</b></div>`;$('event-modal').classList.add('open');$('event-modal').setAttribute('aria-hidden','false')}
function closeEvent(){$('event-modal').classList.remove('open');$('event-modal').setAttribute('aria-hidden','true')}
$('refresh').addEventListener('click',load);$('search-plate').addEventListener('click',load);$('plate-search').addEventListener('keydown',e=>{if(e.key==='Enter')load()});$('event-limit').addEventListener('change',load);$('retention-form').addEventListener('submit',saveRetention);$('mqtt-form').addEventListener('submit',saveMqtt);$('mqtt-test').addEventListener('click',testMqtt);$('camera-filter').addEventListener('change',e=>syncFilter(e.target));$('camera-filter-side').addEventListener('change',e=>syncFilter(e.target));$('apply-filters').addEventListener('click',renderEvents);$('camera-settings').addEventListener('click',()=>toggleDrawer(true));$('camera-settings-side').addEventListener('click',()=>toggleDrawer(true));$('open-cameras').addEventListener('click',()=>toggleDrawer(true));$('close-drawer').addEventListener('click',()=>toggleDrawer(false));$('drawer-backdrop').addEventListener('click',()=>toggleDrawer(false));$('camera-form').addEventListener('submit',addCamera);$('events').addEventListener('click',e=>{const row=e.target.closest('.event-row');if(row)openEvent(row.dataset.eventId)});$('events').addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&e.target.classList.contains('event-row')){e.preventDefault();openEvent(e.target.dataset.eventId)}});$('close-modal').addEventListener('click',closeEvent);$('event-modal').addEventListener('click',e=>{if(e.target===$('event-modal'))closeEvent()});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeEvent()});load();loadSettings();setInterval(load,30000);
