const $=id=>document.getElementById(id);let allEvents=[];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const formatTime=value=>new Date(value).toLocaleString([], {hour:'2-digit',minute:'2-digit',day:'2-digit',month:'short'});
async function load(){try{const[a,e]=await Promise.all([fetch('api/analytics').then(r=>r.json()),fetch('api/events?limit=50').then(r=>r.json())]);$('today').textContent=a.today;$('unique').textContent=a.unique_plates;$('total').textContent=a.total;$('confidence').textContent=a.avg_confidence==null?'—':`${Math.round(a.avg_confidence*100)}%`;$('event-count').textContent=`${e.events.length} EVENTS`;allEvents=e.events;renderChart(a.hourly);renderTop(a.top_plates);renderEvents();renderLatest();loadCameras()}catch(error){console.error('Unable to refresh dashboard',error)}}
function renderChart(data){const max=Math.max(...data.map(x=>x.count),1);$('chart').innerHTML=data.length?data.map(x=>`<div class="bar-wrap"><div class="bar" style="height:${Math.max(4,x.count/max*155)}px" title="${x.count} detections"></div><span class="bar-label">${x.hour}:00</span></div>`).join(''):'<div class="empty">No detections yet</div>'}
function renderTop(data){const max=data[0]?.count||1;$('top').innerHTML=data.length?data.map(x=>`<div class="top-row"><strong>${esc(x.plate)}</strong><span>${x.count} detections</span><div class="track"><div class="fill" style="width:${x.count/max*100}%"></div></div></div>`).join(''):'<div class="empty">No plates yet</div>'}
function renderEvents(){const filter=$('camera-filter').value,data=filter?allEvents.filter(x=>x.camera===filter):allEvents;$('events').innerHTML=data.length?data.map(x=>`<tr><td>${formatTime(x.captured_at)}</td><td>${esc(x.plate)}</td><td>${esc(x.camera)}</td><td><span class="type-tag">${esc(x.vehicle_type)}</span></td><td class="confidence">${x.confidence==null?'—':Math.round(x.confidence*100)+'%'}</td></tr>`).join(''):'<tr><td colspan="5" class="empty">No detections for this camera.</td></tr>'}
function renderLatest(){const event=allEvents[0];$('latest-plate').textContent=event?.plate||'—';$('latest-camera').textContent=event?.camera||'—';$('latest-time').textContent=event?formatTime(event.captured_at):'—'}
async function loadCameras(){const data=await fetch('api/cameras').then(r=>r.json());const selected=$('camera-filter').value;const options='<option value="">All cameras</option>'+data.cameras.map(c=>`<option value="${esc(c.name)}">${esc(c.name)}</option>`).join('');$('camera-filter').innerHTML=options;$('camera-filter-side').innerHTML=options;$('camera-filter').value=selected;$('camera-filter-side').value=selected;$('camera-count').textContent=data.cameras.length;$('camera-list').innerHTML=data.cameras.length?data.cameras.map(c=>`<div class="camera-item"><span class="camera-status"></span><div><strong>${esc(c.name)}</strong><small>${esc(c.location||'Location not set')}</small></div><button class="delete-camera" data-id="${c.id}" title="Remove camera">×</button></div>`).join(''):'<div class="empty">No cameras configured yet.</div>';$('network-cameras').innerHTML=data.cameras.length?data.cameras.slice(0,4).map(c=>`<div><i class="dot lime"></i><span>${esc(c.name)}</span><small>${esc(c.location||'Online')}</small></div>`).join(''):'<div class="empty">No cameras configured</div>';document.querySelectorAll('.delete-camera').forEach(b=>b.onclick=async()=>{if(confirm('Remove this camera?')){await fetch('api/cameras/'+b.dataset.id,{method:'DELETE'});loadCameras()}})}
async function addCamera(e){e.preventDefault();const body=Object.fromEntries(new FormData(e.target));const res=await fetch('api/cameras',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(res.ok){e.target.reset();loadCameras()}else{const err=await res.json();alert(err.error||'Could not add camera')}}
function syncFilter(source){const value=source.value;$('camera-filter').value=value;$('camera-filter-side').value=value;renderEvents()}
function toggleDrawer(open){$('camera-drawer').classList.toggle('open',open);$('drawer-backdrop').classList.toggle('open',open)}
$('refresh').addEventListener('click',load);$('camera-filter').addEventListener('change',e=>syncFilter(e.target));$('camera-filter-side').addEventListener('change',e=>syncFilter(e.target));$('apply-filters').addEventListener('click',renderEvents);$('camera-settings').addEventListener('click',()=>toggleDrawer(true));$('camera-settings-side').addEventListener('click',()=>toggleDrawer(true));$('open-cameras').addEventListener('click',()=>toggleDrawer(true));$('close-drawer').addEventListener('click',()=>toggleDrawer(false));$('drawer-backdrop').addEventListener('click',()=>toggleDrawer(false));$('camera-form').addEventListener('submit',addCamera);load();setInterval(load,30000);
